#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d  1 2 3 
bspc monitor VGA-1 -d   4 5 6 7 8 9 
bspc monitor VGA-1 -s HDMI-1 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a zathura desktop='^1' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a Telegram-desktop desktop='^8'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

xrandr --output VGA-1  --rotate left --mode 1680x1050_60 --left-of HDMI-1 
xrandr --output HDMI-1 --primary --mode 1920x1080  --rotate normal
xrandr --output eDP-1 --off

#xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --output VGA-1 --off 
#xrandr --output HDMI-1 --mode 1920x1080 --rotate normal

$HOME/.config/polybar/launch.sh

bspc config top_padding 30
bspc config bottom_padding 0
bspc config focused_border_color  \#5199FF 
bspc config border_width 3


feh --bg-fill ~/.config/wallpaper/left-1.jpg  ~/.config/wallpaper/center-1.jpg

setxkbmap ru ruchey_latin

